// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkOKv2JwNuQ5J1Tmi_RK1T6gEnshyp-60',
    appId: '1:530592230453:web:3cbee64763d09162d4d57c',
    messagingSenderId: '530592230453',
    projectId: 'get-data-and-display',
    authDomain: 'get-data-and-display.firebaseapp.com',
    storageBucket: 'get-data-and-display.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9LEBKBHYH-Nj1-gr18PJJ-uxvqPbzAAA',
    appId: '1:530592230453:android:62d56aa67151eb8ad4d57c',
    messagingSenderId: '530592230453',
    projectId: 'get-data-and-display',
    storageBucket: 'get-data-and-display.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDxn7VtChyETRafdI4CldL01qGc4IyJy8',
    appId: '1:530592230453:ios:7192c98242ac709cd4d57c',
    messagingSenderId: '530592230453',
    projectId: 'get-data-and-display',
    storageBucket: 'get-data-and-display.appspot.com',
    iosBundleId: 'com.example.getDataAndDisplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDxn7VtChyETRafdI4CldL01qGc4IyJy8',
    appId: '1:530592230453:ios:7192c98242ac709cd4d57c',
    messagingSenderId: '530592230453',
    projectId: 'get-data-and-display',
    storageBucket: 'get-data-and-display.appspot.com',
    iosBundleId: 'com.example.getDataAndDisplay',
  );
}
